### ISSUE TITLE
Measure ITMY-ACC noise level

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMY#1]
### Todo
- [ ] take out from the stage to  the table
- [ ] use 3 channel correlation analysis

### Check pint
- [ ] calibration factors?
- [ ]

**Comment by YoshinoriFujii** [comment]
**calibration factors measured by KO:**  

S/N | calibration factor _calib_[count/(m/s**2)] | calibration factor in[(um/s**2)/count], 1e6/_calib_ | Note
-- | -- | -- | --
SN #4 | 181079.078 | 5.52244914788 |  
SN #5 | -189066 | -5.28915828335 |  
SN #7 | -189119.217 | -5.28766994631 |  
SN #8 | 171528.487 | 5.82993 |

### result
- just seismic noise measurement with the accelerometers and seismometers.
- Since the air-shielding system was not perfect, the noise at lower frequency region was quite noisy.

[acc_seismic-noise_spectra_summary.pdf](https://github.com/gw-vis/ITMY/files/2638184/acc_seismic-noise_spectra_summary.pdf)

**Comment by YoshinoriFujii** [comment]
> use 3 channel correlation analysis

I have to improve the air-shielding system, otherwise I will obtain un-coherent signals and will not be available to use 3-channel correlation analysis.

![image](https://user-images.githubusercontent.com/37787512/49354924-95cf7400-f708-11e8-9b70-1852f1141778.png)

**Comment by YoshinoriFujii** [comment]
They are on the IP-stage.
- [ ] try to input torque in Yaw and check if all the accelerometers have same amplitude
