### ISSUE TITLE
Install 1 STM driver for GAS

### ISSUE THREAD

**Issue by gw-vis** [gw-vis/ITMY#2]
### Todo
- [ ] install and configure

### check point
- [ ] is the driver accessible?
- [ ] does the motor work properly?

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=6786

**Comment by YoshinoriFujii** [comment]
IP-STM worked.
GAS-STM will be still checked.
