### ISSUE TITLE
all the TFs are to be measured

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMY#5]
## 歴史
- IYC will be pumped down on Jan 14th and the preparation for simple damping control should be finished.

## todo
- [ ] implement the IP-LVDT-sensor matrix
- [ ] measure/implement IP-actuator matrix
- [ ] implement the BF-LVDT-sensor matrix
- [ ] measure TF 

## Assignees
@YoshinoriFujii 
and someone else...
