### ISSUE TITLE
IP-sensors/actuators is to be aligned to interferometer frame

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMY#6]
### todo
- [ ] align LVDT-sensor matrix to interferometer frame.
- [ ] diagonalize the actuator matrix with 2Hz line.
- [ ] measure TFs by LVDTs.
- [ ] inter-calibrate the ACC with LVDT. 
- [ ] diagonalize the ACC-sensor matrix

### additional todo
- [ ] diagonalize the actuator matrix with 3Hz line.

**Comment by YoshinoriFujii** [comment]
> align LVDT-sensor matrix to interferometer frame.

### reference
[1] /users/VIS/TypeA/ITMX/TF/Lucia/ITMY/SenSIPITMY.m
[2] [klog#7468]("http://klog.icrr.u-tokyo.ac.jp/osl/?r=7468" klog#7468)

**Comment by YoshinoriFujii** [comment]
- [X] calibration factors of LVDT-H{1/2/3} was correctly implemented.  
ref: klog5829 http://klog.icrr.u-tokyo.ac.jp/osl/?r=5829

- [ ] check if the positive input to COUILOUT_IN makes positive displacement to LVDT-H{1/2/3}_OUT

**Comment by YoshinoriFujii** [comment]
> diagonalize the actuator matrix with 2Hz line.
measure TFs by LVDTs.

done. The measurement files are stored in;
/users/VIS/TypeA/ITMY/measurement/TF/181226/diag_test/coil_corrected/*

**Comment by YoshinoriFujii** [comment]
file:///users/VIS/TypeA/ITMY/measurement/spectra/181227/IP_cntrol_comp_181227_1207JST.png
