### ISSUE TITLE
Tower part characterization

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ITMY#8]
### Todo
- Measure the mechanical transfer function
  - [ ] IP (L/T/Y)
  - [ ] BF (L/T/V/R/P/Y)
  - [X] GAS filters (F1/F2/F3/BF)

#### = IP =
- [X] LVDT sensor Mat daig
- [X] Actuator Mat diag with 2Hz line
- [ ] calculate mechanical couping of IP

#### =  BF =
- [ ]

**Comment by YoshinoriFujii** [comment]
> - [ ] Measure the mechanical transfer function
>    - [X] GAS filters (F1/F2/F3/BF)

`/users/VIS/TypeA/ITMY/measurement/TF/181229/`
